server:
  port: 8080

#spring:
#  datasource:
#    druid:
#      url: jdbc:mysql://localhost:3306/datasource_one?serverTimezone=UTC
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 123456

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      datasource1:
        url: jdbc:mysql://localhost:3306/datasource_one?serverTimezone=UTC
        username: root
        password: 123456
      datasource2:
        url: jdbc:mysql://localhost:3306/datasource_two?serverTimezone=UTC
        username: root
        password: 123456


mybatis:
  mapper-locations: classpath:mappers/**/*.xml
